version: 2
jobs:
  build:
    docker:
    - image: circleci/node:latest
    steps:
    - checkout
    - run:
        name: "Instalando dependências"
        command: npm install
    - save_cache:
        key: v1-nm-{{ .Environment.CIRCLE_SHA1 }}
        paths:
        - ~/node_modules

  test:
    docker:
      - image: circleci/node:latest
    steps:
      - restore_cache:
        key: v1-nm-{{ .Environment.CIRCLE_SHA1 }}
      - run:
        name: "Running tests"
        command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
          - build


