version: 2
jobs:
  build:
    docker:
    - image: circleci/node:latest
    steps:
    - checkout
    - run:
        name: "Instalando dependências"
        command: npm install
    - run:
        name: "Running tests"
        command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: master


